name: Build_Docker_CI

on:
  schedule:
    - cron: '0 18 * * 0,2,4,6'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          show-progress: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: RUN_CI
        id : RUN_CI
        run : |
            sudo apt-get install git bash -y && \
            git clone https://github.com/tailscale/tailscale && \
            cd tailscale && \
            sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go && \
            cd ../tailscale/cmd/derper && \
            go build -buildvcs=false -ldflags "-s -w" -o ./derper 

      - name: Set CURRENT_DATE
        id: set-current-date
        run: |
            echo "CURRENT_DATE_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV  

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.CURRENT_DATE_TIME }}_${{ github.ref_name }}"
          files: '**/derper'
        env:
          GITHUB_TOKEN: ${{ secrets.DUBUX }}              