name: Build_Release

on:
  schedule:
    - cron: '0 18 * * 0,2,4,6'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          show-progress: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: RUN_CI
        id : RUN_CI
        run : |
           docker build -t ci:latest .
           docker run -itd ci:latest
           docker cp ci:/app ./

      - name: Set CURRENT_DATE
        id: set-current-date
        run: |
            echo "CURRENT_DATE_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV  

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.CURRENT_DATE_TIME }}_${{ github.ref_name }}"
          files: './app/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              